run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-use-default: false
