ALTER TABLE users
ALTER COLUMN password_hash SET DEFAULT '',
ALTER COLUMN password_hash SET NOT NULL,
ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'UTC',
ALTER COLUMN created_at SET DEFAULT NOW(),
ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'UTC',
ALTER COLUMN updated_at SET DEFAULT NOW();

UPDATE users
SET password_hash = ''
WHERE password_hash IS NULL;
