ALTER TABLE users
DROP CONSTRAINT IF EXISTS users_email_key;

UPDATE users
SET password_hash = NULLIF(btrim(password_hash), '');

ALTER TABLE users
ALTER COLUMN email TYPE VARCHAR(255),
ALTER COLUMN full_name TYPE VARCHAR(150),
ALTER COLUMN password_hash TYPE VARCHAR(255),
ALTER COLUMN password_hash SET NOT NULL;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS username VARCHAR(50),
ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS phone VARCHAR(20),
ADD COLUMN IF NOT EXISTS job_title VARCHAR(100),
ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS users_email_active_unique_idx
ON users (LOWER(email))
WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS users_username_active_unique_idx
ON users (LOWER(username))
WHERE deleted_at IS NULL AND username IS NOT NULL;
