// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserWithPassword = `-- name: CreateUserWithPassword :one
INSERT INTO users (
  id,
  email,
  password_hash,
  full_name
)
VALUES (
  $1,
  $2,
  $3,
  NULL
)
RETURNING id, email, full_name, username, avatar_url, phone, job_title, status, password_changed_at, created_at, updated_at, deleted_at
`

type CreateUserWithPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

type CreateUserWithPasswordRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FullName          pgtype.Text        `json:"full_name"`
	Username          pgtype.Text        `json:"username"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Phone             pgtype.Text        `json:"phone"`
	JobTitle          pgtype.Text        `json:"job_title"`
	Status            string             `json:"status"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (CreateUserWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, createUserWithPassword, arg.ID, arg.Email, arg.PasswordHash)
	var i CreateUserWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Username,
		&i.AvatarUrl,
		&i.Phone,
		&i.JobTitle,
		&i.Status,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id,
  email,
  full_name,
  username,
  avatar_url,
  phone,
  job_title,
  status,
  COALESCE(password_hash, '') AS password_hash,
  password_changed_at,
  created_at,
  updated_at,
  deleted_at
FROM users
WHERE email = $1
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FullName          pgtype.Text        `json:"full_name"`
	Username          pgtype.Text        `json:"username"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Phone             pgtype.Text        `json:"phone"`
	JobTitle          pgtype.Text        `json:"job_title"`
	Status            string             `json:"status"`
	PasswordHash      string             `json:"password_hash"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Username,
		&i.AvatarUrl,
		&i.Phone,
		&i.JobTitle,
		&i.Status,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByIDForAuthProfile = `-- name: GetUserByIDForAuthProfile :one
SELECT id, email, full_name, username, avatar_url, phone, job_title, status, password_changed_at, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserByIDForAuthProfileRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FullName          pgtype.Text        `json:"full_name"`
	Username          pgtype.Text        `json:"username"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Phone             pgtype.Text        `json:"phone"`
	JobTitle          pgtype.Text        `json:"job_title"`
	Status            string             `json:"status"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetUserByIDForAuthProfile(ctx context.Context, id uuid.UUID) (GetUserByIDForAuthProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDForAuthProfile, id)
	var i GetUserByIDForAuthProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Username,
		&i.AvatarUrl,
		&i.Phone,
		&i.JobTitle,
		&i.Status,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
