// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserWithPassword = `-- name: CreateUserWithPassword :one
INSERT INTO users (
  id,
  email,
  full_name,
  password_hash
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, email, full_name, created_at, updated_at
`

type CreateUserWithPasswordParams struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	FullName     string      `json:"full_name"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

type CreateUserWithPasswordRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (CreateUserWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, createUserWithPassword,
		arg.ID,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
	)
	var i CreateUserWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id,
  email,
  full_name,
  COALESCE(password_hash, '') AS password_hash,
  created_at,
  updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	FullName     string             `json:"full_name"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIDForAuthProfile = `-- name: GetUserByIDForAuthProfile :one
SELECT id, email, full_name, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDForAuthProfileRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByIDForAuthProfile(ctx context.Context, id uuid.UUID) (GetUserByIDForAuthProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDForAuthProfile, id)
	var i GetUserByIDForAuthProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
