// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserWithPassword = `-- name: CreateUserWithPassword :one
INSERT INTO users (
  id,
  email,
  password_hash,
  full_name,
  is_verified,
  status
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, email, full_name, is_verified, status, password_changed_at, created_at, updated_at, deleted_at
`

type CreateUserWithPasswordParams struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FullName     pgtype.Text `json:"full_name"`
	IsVerified   bool        `json:"is_verified"`
	Status       string      `json:"status"`
}

type CreateUserWithPasswordRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FullName          pgtype.Text        `json:"full_name"`
	IsVerified        bool               `json:"is_verified"`
	Status            string             `json:"status"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (CreateUserWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, createUserWithPassword,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.IsVerified,
		arg.Status,
	)
	var i CreateUserWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsVerified,
		&i.Status,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id,
  email,
  full_name,
  is_verified,
  status,
  COALESCE(password_hash, '') AS password_hash,
  password_changed_at,
  created_at,
  updated_at,
  deleted_at
FROM users
WHERE email = $1
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FullName          pgtype.Text        `json:"full_name"`
	IsVerified        bool               `json:"is_verified"`
	Status            string             `json:"status"`
	PasswordHash      string             `json:"password_hash"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsVerified,
		&i.Status,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByIDForAuthProfile = `-- name: GetUserByIDForAuthProfile :one
SELECT id, email, full_name, is_verified, status, password_changed_at, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserByIDForAuthProfileRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FullName          pgtype.Text        `json:"full_name"`
	IsVerified        bool               `json:"is_verified"`
	Status            string             `json:"status"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetUserByIDForAuthProfile(ctx context.Context, id uuid.UUID) (GetUserByIDForAuthProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDForAuthProfile, id)
	var i GetUserByIDForAuthProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsVerified,
		&i.Status,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :one
UPDATE users
SET
  is_verified = true,
  updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, email, full_name, is_verified, status, password_changed_at, created_at, updated_at, deleted_at
`

type MarkUserEmailVerifiedRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FullName          pgtype.Text        `json:"full_name"`
	IsVerified        bool               `json:"is_verified"`
	Status            string             `json:"status"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id uuid.UUID) (MarkUserEmailVerifiedRow, error) {
	row := q.db.QueryRow(ctx, markUserEmailVerified, id)
	var i MarkUserEmailVerifiedRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsVerified,
		&i.Status,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const resetUserPassword = `-- name: ResetUserPassword :one
UPDATE users
SET
  password_hash = $2,
  password_changed_at = NOW(),
  updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, email, full_name, is_verified, status, password_changed_at, created_at, updated_at, deleted_at
`

type ResetUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

type ResetUserPasswordRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FullName          pgtype.Text        `json:"full_name"`
	IsVerified        bool               `json:"is_verified"`
	Status            string             `json:"status"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ResetUserPassword(ctx context.Context, arg ResetUserPasswordParams) (ResetUserPasswordRow, error) {
	row := q.db.QueryRow(ctx, resetUserPassword, arg.ID, arg.PasswordHash)
	var i ResetUserPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsVerified,
		&i.Status,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
