// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	FullName     string             `json:"full_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
