// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const changePassword = `-- name: ChangePassword :exec
UPDATE users
SET
    password_hash = $2,
    password_changed_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type ChangePasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) error {
	_, err := q.db.Exec(ctx, changePassword, arg.ID, arg.PasswordHash)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT 
    id, email, full_name, avatar_key, phone, job_title, 
    is_verified, status, created_at, updated_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetProfileRow struct {
	ID         uuid.UUID          `json:"id"`
	Email      string             `json:"email"`
	FullName   pgtype.Text        `json:"full_name"`
	AvatarKey  pgtype.Text        `json:"avatar_key"`
	Phone      pgtype.Text        `json:"phone"`
	JobTitle   pgtype.Text        `json:"job_title"`
	IsVerified bool               `json:"is_verified"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProfile(ctx context.Context, id uuid.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i GetProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarKey,
		&i.Phone,
		&i.JobTitle,
		&i.IsVerified,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT password_hash
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const updateAvatarKey = `-- name: UpdateAvatarKey :exec
UPDATE users
SET
    avatar_key = $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateAvatarKeyParams struct {
	ID        uuid.UUID   `json:"id"`
	AvatarKey pgtype.Text `json:"avatar_key"`
}

func (q *Queries) UpdateAvatarKey(ctx context.Context, arg UpdateAvatarKeyParams) error {
	_, err := q.db.Exec(ctx, updateAvatarKey, arg.ID, arg.AvatarKey)
	return err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE users
SET
    full_name = CASE WHEN $2::boolean THEN $3 ELSE full_name END,
    phone = CASE WHEN $4::boolean THEN $5 ELSE phone END,
    job_title = CASE WHEN $6::boolean THEN $7 ELSE job_title END,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, full_name, avatar_key, phone, job_title, is_verified, status, created_at, updated_at
`

type UpdateProfileParams struct {
	ID             uuid.UUID   `json:"id"`
	UpdateFullName bool        `json:"update_full_name"`
	FullName       pgtype.Text `json:"full_name"`
	UpdatePhone    bool        `json:"update_phone"`
	Phone          pgtype.Text `json:"phone"`
	UpdateJobTitle bool        `json:"update_job_title"`
	JobTitle       pgtype.Text `json:"job_title"`
}

type UpdateProfileRow struct {
	ID         uuid.UUID          `json:"id"`
	Email      string             `json:"email"`
	FullName   pgtype.Text        `json:"full_name"`
	AvatarKey  pgtype.Text        `json:"avatar_key"`
	Phone      pgtype.Text        `json:"phone"`
	JobTitle   pgtype.Text        `json:"job_title"`
	IsVerified bool               `json:"is_verified"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (UpdateProfileRow, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.UpdateFullName,
		arg.FullName,
		arg.UpdatePhone,
		arg.Phone,
		arg.UpdateJobTitle,
		arg.JobTitle,
	)
	var i UpdateProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarKey,
		&i.Phone,
		&i.JobTitle,
		&i.IsVerified,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
