// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_roles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignSystemRoleToUser = `-- name: AssignSystemRoleToUser :exec
INSERT INTO user_system_roles (
  user_id,
  role_id,
  assigned_by
)
VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AssignSystemRoleToUserParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	RoleID     int64       `json:"role_id"`
	AssignedBy pgtype.UUID `json:"assigned_by"`
}

func (q *Queries) AssignSystemRoleToUser(ctx context.Context, arg AssignSystemRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignSystemRoleToUser, arg.UserID, arg.RoleID, arg.AssignedBy)
	return err
}

const getSystemRoleByCode = `-- name: GetSystemRoleByCode :one
SELECT id, code, name, description, is_system, created_at, updated_at
FROM system_roles
WHERE code = $1
`

func (q *Queries) GetSystemRoleByCode(ctx context.Context, code string) (SystemRole, error) {
	row := q.db.QueryRow(ctx, getSystemRoleByCode, code)
	var i SystemRole
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
