// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id,
    workspace_id,
    creator_id,
    assignee_id,
    title,
    description,
    status,
    priority,
    due_at,
    sprint_points,
    parent_id,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    NOW(),
    NOW()
) RETURNING id, workspace_id, creator_id, assignee_id, title, description, status, priority, due_at, sprint_points, parent_id, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	ID           uuid.UUID          `json:"id"`
	WorkspaceID  uuid.UUID          `json:"workspace_id"`
	CreatorID    uuid.UUID          `json:"creator_id"`
	AssigneeID   pgtype.UUID        `json:"assignee_id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Status       string             `json:"status"`
	Priority     string             `json:"priority"`
	DueAt        pgtype.Timestamptz `json:"due_at"`
	SprintPoints pgtype.Int4        `json:"sprint_points"`
	ParentID     pgtype.UUID        `json:"parent_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.WorkspaceID,
		arg.CreatorID,
		arg.AssigneeID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueAt,
		arg.SprintPoints,
		arg.ParentID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.SprintPoints,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, workspace_id, creator_id, assignee_id, title, description, status, priority, due_at, sprint_points, parent_id, created_at, updated_at, deleted_at FROM tasks
WHERE id = $1
  AND workspace_id = $2
  AND deleted_at IS NULL
`

type GetTaskByIDParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.SprintPoints,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTasksByWorkspace = `-- name: ListTasksByWorkspace :many
SELECT id, workspace_id, creator_id, assignee_id, title, description, status, priority, due_at, sprint_points, parent_id, created_at, updated_at, deleted_at FROM tasks
WHERE workspace_id = $1
  AND ($2::boolean OR deleted_at IS NULL)
  AND ($3::varchar IS NULL OR status = $3::varchar)
  AND ($4::uuid IS NULL OR assignee_id = $4::uuid)
  AND ($5::uuid IS NULL OR parent_id = $5::uuid)
  AND ($6::timestamptz IS NULL OR due_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR due_at <= $7::timestamptz)
ORDER BY created_at DESC
`

type ListTasksByWorkspaceParams struct {
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	IncludeDeleted bool               `json:"include_deleted"`
	Status         pgtype.Text        `json:"status"`
	AssigneeID     pgtype.UUID        `json:"assignee_id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	DueFrom        pgtype.Timestamptz `json:"due_from"`
	DueTo          pgtype.Timestamptz `json:"due_to"`
}

func (q *Queries) ListTasksByWorkspace(ctx context.Context, arg ListTasksByWorkspaceParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByWorkspace,
		arg.WorkspaceID,
		arg.IncludeDeleted,
		arg.Status,
		arg.AssigneeID,
		arg.ParentID,
		arg.DueFrom,
		arg.DueTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatorID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueAt,
			&i.SprintPoints,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
  AND workspace_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteTaskParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error {
	_, err := q.db.Exec(ctx, softDeleteTask, arg.ID, arg.WorkspaceID)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    title = CASE
        WHEN $1::boolean THEN $2::varchar
        ELSE title
    END,
    description = CASE
        WHEN $3::boolean THEN $4::text
        ELSE description
    END,
    status = CASE
        WHEN $5::boolean THEN $6::varchar
        ELSE status
    END,
    priority = CASE
        WHEN $7::boolean THEN $8::varchar
        ELSE priority
    END,
    due_at = CASE
        WHEN $9::boolean THEN $10::timestamptz
        ELSE due_at
    END,
    sprint_points = CASE
        WHEN $11::boolean THEN $12::int
        ELSE sprint_points
    END,
    assignee_id = CASE
        WHEN $13::boolean THEN $14::uuid
        ELSE assignee_id
    END,
    parent_id = CASE
        WHEN $15::boolean THEN $16::uuid
        ELSE parent_id
    END,
    updated_at = NOW()
WHERE id = $17
  AND workspace_id = $18
  AND deleted_at IS NULL
RETURNING id, workspace_id, creator_id, assignee_id, title, description, status, priority, due_at, sprint_points, parent_id, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	UpdateTitle        bool               `json:"update_title"`
	Title              string             `json:"title"`
	UpdateDescription  bool               `json:"update_description"`
	Description        pgtype.Text        `json:"description"`
	UpdateStatus       bool               `json:"update_status"`
	Status             string             `json:"status"`
	UpdatePriority     bool               `json:"update_priority"`
	Priority           string             `json:"priority"`
	UpdateDueAt        bool               `json:"update_due_at"`
	DueAt              pgtype.Timestamptz `json:"due_at"`
	UpdateSprintPoints bool               `json:"update_sprint_points"`
	SprintPoints       pgtype.Int4        `json:"sprint_points"`
	UpdateAssigneeID   bool               `json:"update_assignee_id"`
	AssigneeID         pgtype.UUID        `json:"assignee_id"`
	UpdateParentID     bool               `json:"update_parent_id"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.UpdateTitle,
		arg.Title,
		arg.UpdateDescription,
		arg.Description,
		arg.UpdateStatus,
		arg.Status,
		arg.UpdatePriority,
		arg.Priority,
		arg.UpdateDueAt,
		arg.DueAt,
		arg.UpdateSprintPoints,
		arg.SprintPoints,
		arg.UpdateAssigneeID,
		arg.AssigneeID,
		arg.UpdateParentID,
		arg.ParentID,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.SprintPoints,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
