// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id,
  email,
  password_hash,
  full_name,
  is_verified,
  status,
  password_changed_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  NOW()
)
RETURNING id, email, full_name, is_verified, status, password_changed_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FullName     pgtype.Text `json:"full_name"`
	IsVerified   bool        `json:"is_verified"`
	Status       string      `json:"status"`
}

type CreateUserRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FullName          pgtype.Text        `json:"full_name"`
	IsVerified        bool               `json:"is_verified"`
	Status            string             `json:"status"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.IsVerified,
		arg.Status,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsVerified,
		&i.Status,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
UPDATE users
SET
  deleted_at = NOW(),
  updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	err := row.Scan(&id)
	return id, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, full_name, is_verified, status, password_changed_at, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FullName          pgtype.Text        `json:"full_name"`
	IsVerified        bool               `json:"is_verified"`
	Status            string             `json:"status"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsVerified,
		&i.Status,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, full_name, is_verified, status, password_changed_at, created_at, updated_at, deleted_at
FROM users
WHERE deleted_at IS NULL
  AND ($1::varchar IS NULL OR status = $1::varchar)
  AND (
    $2::varchar IS NULL
    OR email ILIKE '%' || $2::varchar || '%'
    OR COALESCE(full_name, '') ILIKE '%' || $2::varchar || '%'
  )
ORDER BY created_at DESC
`

type ListUsersParams struct {
	Status pgtype.Text `json:"status"`
	Search pgtype.Text `json:"search"`
}

type ListUsersRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FullName          pgtype.Text        `json:"full_name"`
	IsVerified        bool               `json:"is_verified"`
	Status            string             `json:"status"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Status, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.IsVerified,
			&i.Status,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users
SET
  deleted_at = NULL,
  updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NOT NULL
RETURNING id, email, full_name, is_verified, status, password_changed_at, created_at, updated_at, deleted_at
`

type RestoreUserRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FullName          pgtype.Text        `json:"full_name"`
	IsVerified        bool               `json:"is_verified"`
	Status            string             `json:"status"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) RestoreUser(ctx context.Context, id uuid.UUID) (RestoreUserRow, error) {
	row := q.db.QueryRow(ctx, restoreUser, id)
	var i RestoreUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsVerified,
		&i.Status,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  full_name = CASE WHEN $1::bool THEN $2::varchar(150) ELSE full_name END,
  password_hash = CASE WHEN $3::bool THEN $4::varchar(255) ELSE password_hash END,
  password_changed_at = CASE WHEN $3::bool THEN NOW() ELSE password_changed_at END,
  updated_at = NOW()
WHERE id = $5
  AND deleted_at IS NULL
RETURNING id, email, full_name, is_verified, status, password_changed_at, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	SetFullName     bool        `json:"set_full_name"`
	FullName        pgtype.Text `json:"full_name"`
	SetPasswordHash bool        `json:"set_password_hash"`
	PasswordHash    string      `json:"password_hash"`
	ID              uuid.UUID   `json:"id"`
}

type UpdateUserRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FullName          pgtype.Text        `json:"full_name"`
	IsVerified        bool               `json:"is_verified"`
	Status            string             `json:"status"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.SetFullName,
		arg.FullName,
		arg.SetPasswordHash,
		arg.PasswordHash,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsVerified,
		&i.Status,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
