// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_member.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :one
INSERT INTO workspace_members (
    id, workspace_id, user_id, role, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, NOW(), NOW()
) RETURNING id, workspace_id, user_id, role, created_at, updated_at
`

type AddWorkspaceMemberParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, addWorkspaceMember,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
	)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countWorkspaceMembersByRole = `-- name: CountWorkspaceMembersByRole :one
SELECT COUNT(*) FROM workspace_members
WHERE workspace_id = $1 AND role = $2
`

type CountWorkspaceMembersByRoleParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Role        string    `json:"role"`
}

func (q *Queries) CountWorkspaceMembersByRole(ctx context.Context, arg CountWorkspaceMembersByRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceMembersByRole, arg.WorkspaceID, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :exec
DELETE FROM workspace_members
WHERE id = $1
`

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceMember, id)
	return err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT id, workspace_id, user_id, role, created_at, updated_at FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceMemberWithUserInfo = `-- name: GetWorkspaceMemberWithUserInfo :one
SELECT
    wm.id, wm.workspace_id, wm.user_id, wm.role, wm.created_at, wm.updated_at,
    u.email, u.full_name, u.avatar_key, u.status AS user_status
FROM workspace_members wm
JOIN users u ON wm.user_id = u.id
WHERE wm.workspace_id = $1 AND wm.user_id = $2
`

type GetWorkspaceMemberWithUserInfoParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

type GetWorkspaceMemberWithUserInfoRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Email       string             `json:"email"`
	FullName    pgtype.Text        `json:"full_name"`
	AvatarKey   pgtype.Text        `json:"avatar_key"`
	UserStatus  string             `json:"user_status"`
}

func (q *Queries) GetWorkspaceMemberWithUserInfo(ctx context.Context, arg GetWorkspaceMemberWithUserInfoParams) (GetWorkspaceMemberWithUserInfoRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMemberWithUserInfo, arg.WorkspaceID, arg.UserID)
	var i GetWorkspaceMemberWithUserInfoRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.FullName,
		&i.AvatarKey,
		&i.UserStatus,
	)
	return i, err
}

const listWorkspaceMembersByWorkspace = `-- name: ListWorkspaceMembersByWorkspace :many
SELECT 
    wm.id, wm.workspace_id, wm.user_id, wm.role, wm.created_at, wm.updated_at,
    u.email, u.full_name, u.avatar_key, u.status AS user_status
FROM workspace_members wm
JOIN users u ON wm.user_id = u.id
WHERE wm.workspace_id = $1
ORDER BY wm.created_at ASC
`

type ListWorkspaceMembersByWorkspaceRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Email       string             `json:"email"`
	FullName    pgtype.Text        `json:"full_name"`
	AvatarKey   pgtype.Text        `json:"avatar_key"`
	UserStatus  string             `json:"user_status"`
}

func (q *Queries) ListWorkspaceMembersByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceMembersByWorkspaceRow
	for rows.Next() {
		var i ListWorkspaceMembersByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.FullName,
			&i.AvatarKey,
			&i.UserStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE workspace_members
SET role = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, user_id, role, created_at, updated_at
`

type UpdateMemberRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.ID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
