// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkSlugExists = `-- name: CheckSlugExists :one
SELECT EXISTS(
    SELECT 1 FROM workspaces 
    WHERE slug = $1 AND ($2::uuid IS NULL OR id != $2::uuid)
)
`

type CheckSlugExistsParams struct {
	Slug      string      `json:"slug"`
	ExcludeID pgtype.UUID `json:"exclude_id"`
}

func (q *Queries) CheckSlugExists(ctx context.Context, arg CheckSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSlugExists, arg.Slug, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (
    id, name, slug, description, owner_user_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, NOW(), NOW()
) RETURNING id, name, slug, description, owner_user_id, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	OwnerUserID uuid.UUID   `json:"owner_user_id"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.OwnerUserID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces
WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, slug, description, owner_user_id, created_at, updated_at
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, name, slug, description, owner_user_id, created_at, updated_at
FROM workspaces
WHERE slug = $1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspacesByOwner = `-- name: ListWorkspacesByOwner :many
SELECT id, name, slug, description, owner_user_id, created_at, updated_at
FROM workspaces
WHERE owner_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkspacesByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET
    name = CASE WHEN $2::boolean THEN $3::varchar ELSE name END,
    slug = CASE WHEN $4::boolean THEN $5::varchar ELSE slug END,
    description = CASE WHEN $6::boolean THEN $7 ELSE description END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, description, owner_user_id, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	ID                uuid.UUID   `json:"id"`
	UpdateName        bool        `json:"update_name"`
	Name              string      `json:"name"`
	UpdateSlug        bool        `json:"update_slug"`
	Slug              string      `json:"slug"`
	UpdateDescription bool        `json:"update_description"`
	Description       pgtype.Text `json:"description"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.ID,
		arg.UpdateName,
		arg.Name,
		arg.UpdateSlug,
		arg.Slug,
		arg.UpdateDescription,
		arg.Description,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
