// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_invitation.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countPendingInvitationsByEmail = `-- name: CountPendingInvitationsByEmail :one
SELECT COUNT(*) FROM workspace_invitations
WHERE LOWER(email) = LOWER($1)
`

func (q *Queries) CountPendingInvitationsByEmail(ctx context.Context, lower string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingInvitationsByEmail, lower)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspaceInvitation = `-- name: CreateWorkspaceInvitation :one
INSERT INTO workspace_invitations (
    id,
    workspace_id,
    email,
    token,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    LOWER($3),
    $4,
    NOW(),
    NOW()
) RETURNING id, workspace_id, email, token, created_at, updated_at
`

type CreateWorkspaceInvitationParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Lower       string    `json:"lower"`
	Token       string    `json:"token"`
}

func (q *Queries) CreateWorkspaceInvitation(ctx context.Context, arg CreateWorkspaceInvitationParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, createWorkspaceInvitation,
		arg.ID,
		arg.WorkspaceID,
		arg.Lower,
		arg.Token,
	)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspaceInvitation = `-- name: DeleteWorkspaceInvitation :exec
DELETE FROM workspace_invitations
WHERE id = $1
`

func (q *Queries) DeleteWorkspaceInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceInvitation, id)
	return err
}

const getWorkspaceInvitationByEmailAndWorkspace = `-- name: GetWorkspaceInvitationByEmailAndWorkspace :one
SELECT id, workspace_id, email, token, created_at, updated_at FROM workspace_invitations
WHERE workspace_id = $2 AND LOWER(email) = LOWER($1)
LIMIT 1
`

type GetWorkspaceInvitationByEmailAndWorkspaceParams struct {
	Lower       string    `json:"lower"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetWorkspaceInvitationByEmailAndWorkspace(ctx context.Context, arg GetWorkspaceInvitationByEmailAndWorkspaceParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, getWorkspaceInvitationByEmailAndWorkspace, arg.Lower, arg.WorkspaceID)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceInvitationByID = `-- name: GetWorkspaceInvitationByID :one
SELECT id, workspace_id, email, token, created_at, updated_at FROM workspace_invitations
WHERE id = $1
`

func (q *Queries) GetWorkspaceInvitationByID(ctx context.Context, id uuid.UUID) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, getWorkspaceInvitationByID, id)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceInvitationByToken = `-- name: GetWorkspaceInvitationByToken :one
SELECT id, workspace_id, email, token, created_at, updated_at FROM workspace_invitations
WHERE token = $1
`

func (q *Queries) GetWorkspaceInvitationByToken(ctx context.Context, token string) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, getWorkspaceInvitationByToken, token)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaceInvitationsByWorkspace = `-- name: ListWorkspaceInvitationsByWorkspace :many
SELECT id, workspace_id, email, token, created_at, updated_at FROM workspace_invitations
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkspaceInvitationsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceInvitation, error) {
	rows, err := q.db.Query(ctx, listWorkspaceInvitationsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceInvitation
	for rows.Next() {
		var i WorkspaceInvitation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Token,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
